### ISSUE TITLE
Click-to-Call

### ISSUE THREAD

**Issue by yourkidding** [BelledonneCommunications/linphone#1]
Hello everyone!

I used much time searching for a click-to-call function for linphone. Unfortunately I found nothing, except other people trying to find something alike :)

Cause of my lacking programming skills: Is there someone who could help with this?

I imagine something like this: mark a number you want to dial -> use a keyboard-shortcut to call in linephone. If there already is an obvious solution, then I am sorry for asking.

Best regards
Sebastian

**Comment by bagage** [comment]
Do you mean calling from within Linphone using a shortcut, or from outside of Linphone?

If this is the first solution, does typing number in address bar then typing [Enter] work?
Otherwise, I think this will be OS specific. Doing a custom key shortcut which will call `linphone -c <entered_number>` will do the trick. However you have to manage how to enter the phone number first (opening a popup?...).

**Comment by yourkidding** [comment]
Nice. This worked - although not what I expected.

There are several click-to-call agents working with marked numbers. Using Thunderbird for example: Opening a contact -> marking (not directly copying) only the phone number -> pressing the costom key -> the phone number is sent to the clipboard -> the agent reads the clipboard -> and calls the number.

I tried more or less everything ... maybe the solution is somwhat simple. but I just dont get it and would really appreciate your help with this.

Best regards
Sebastian

**Comment by bagage** [comment]
This seems to be a Mozilla specific feature - nothing standard unfortunately. Nothing is planned to support it yet but any patch/PR is welcome!
