### ISSUE TITLE
Only English and French UI language options available

### ISSUE THREAD

**Issue by shvchk** [BelledonneCommunications/linphone#40]
I have installed Linphone 4 on Ubuntu 17.10 with Flatpack following instructions on your [downloads page](https://www.linphone.org/technical-corner/linphone/downloads), and there are no UI languages except English and French, although [in this repo there are also other languages](https://github.com/BelledonneCommunications/linphone/tree/master/po) (Russian in particular, which is what I need). It seems that installed Linphone gets translations from `qph` files in `files/phrasebooks/` directory, and along with English and French there are also other languages (13 total now), including Russian, but they are not showed as UI language options in Linphone.

**Comment by Wescoeur** [comment]
Only english and french languages are supported in Linphone Desktop 4.
This [folder](https://github.com/BelledonneCommunications/linphone/tree/master/po) contains ts files for Linphone Desktop 3. For the moment no other trads are available.

If you have other problems with the desktop version, please open your issue here: https://github.com/BelledonneCommunications/linphone-desktop/issues
