### ISSUE TITLE
Python srtp_unprotect_rtcp fails

### ISSUE THREAD

**Issue by psx88** [BelledonneCommunications/linphone#78]
When using the python wrapper and media encryption srtp (SRTP, ZRTP, DTLS) "srtp_unprotect_rtcp()" constantly fails every few seconds with error code 7 (auth fail).

Tested on raspbian and debian (3.10 and 3.12 .whl from linphone.org/snapshots) with the python code provided on the linphone xwiki.

ERROR:root:srtp_unprotect_rtcp() failed (7) on stream ctx

This never happens in following scenarios:

liblinphone project (iOS) <-> liblinphone project (iOS)
iOS official linphone app <-> linphone desktop (debian)
liblinphone project (iOS) <-> linphone desktop (debian)
linphonecsh (debian, raspbian) <-> liblinphone project (iOS)

It seems that this is only happening with the official python wrappers!?

**Comment by smorlat** [comment]
Hi,

This issue is affecting linphone-iphone and linphone-android releases 4.0.x.
They failed to interoperate at SRTCP level (only RTCP is affected) with previous versions and webRTC. It appeared after upgrading libsrtp from 1.x to 2.x.
We just performed a fix in the mediastreamer2 library, who was the culprit (libsrtp-2.x revealed the issue but was not the culprit):

commit 74a1a2f2eaa72296b67e13698f3ba718629ff988 (HEAD -> master, origin/master, origin/HEAD, bc/fix/srtcp_interrop_bug, fix/srtcp_interrop_bug)
Author: Simon Morlat <simon.morlat@linphone.org>
Date:   Tue Feb 19 11:08:44 2019 +0100

    Fix srtp_t initialization. In order to let master key to be different for the RTP and the RTCP streams (which will happen with SRTP-DTLS and no rtcp-mux), we use one srtp_t for RTP and one srtp_t for RTCP.
    However, the derivation of keys from master key requires both SRTP and SRTCP parameters to be known, which was not the case.
    Indeed, the code was only initializing the SRTCP parameters for the srtp_t responsible for RTCP.
    This leads to a wrong computation of the SRTCP auth key, which then creates systematic srtp_unprotect_rtcp() errors.

The upcoming 4.1 release for iOS and Android will have the fix for this issue.

Best regards,

Simon
